# Generated by Django 3.0.8 on 2023-06-01 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('RePick', 'RePick'), ('바리바리', '바리바리'), ('Hooking', 'Hooking'), ('Dansupport', 'Dansupport'), ('TherapEse', 'TherapEse')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part_Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, choices=[('권가은', '권가은'), ('김문기', '김문기'), ('김서연', '김서연'), ('노수진', '노수진'), ('배성준', '배성준'), ('신유진', '신유진'), ('오예린', '이예지'), ('장효신', '장효신'), ('최민주', '최민주'), ('김지원', '김지원'), ('김현수', '김현수'), ('김현우', '김현우'), ('서찬혁', '서찬혁'), ('서혜준', '서혜준'), ('이소정', '이소정'), ('임탁균', '임탁균'), ('조예지', '조예지'), ('최유미', '최유미'), ('황재령', '황재령')], max_length=8, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
