# Generated by Django 3.0.8 on 2023-05-28 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_vote',
            name='team',
            field=models.CharField(choices=[('RePick', 'RePick'), ('바리바리', '바리바리'), ('Hooking', 'Hooking'), ('Dansupport', 'Dansupport'), ('TherapEse', 'TherapEse')], max_length=16),
        ),
        migrations.AlterField(
            model_name='team_vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Part_Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
