# Generated by Django 3.0.8 on 2023-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_vote',
            name='team',
            field=models.CharField(choices=[('RePick', 'RePick'), ('바리바리', '바리바리'), ('Hooking', 'Hooking'), ('Dansupport', 'Dansupport'), ('ThearapEse', 'ThearapEse')], max_length=16),
        ),
    ]
