# Generated by Django 3.0.8 on 2023-06-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20230627_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_vote',
            name='team',
            field=models.CharField(choices=[('RePick', 'RePick'), ('바리바리', '바리바리'), ('Hooking', 'Hooking'), ('Dansupport', 'Dansupport'), ('TherapEase', 'TherapEase')], max_length=16),
        ),
    ]
