# Generated by Django 3.0.8 on 2023-05-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20230528_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part_vote',
            name='leader',
            field=models.CharField(max_length=16),
        ),
    ]
