# Generated by Django 3.0.8 on 2023-05-28 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0003_auto_20230528_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part_vote',
            name='leader',
        ),
        migrations.AddField(
            model_name='part_vote',
            name='vote',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
