# Generated by Django 3.0.8 on 2023-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20230528_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part_vote',
            name='vote',
        ),
        migrations.AddField(
            model_name='part_vote',
            name='part',
            field=models.CharField(default='최유미', max_length=8),
        ),
    ]
