# Generated by Django 3.0.8 on 2023-05-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_auto_20230528_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part_vote',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='part_vote',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='part_vote',
            name='part',
            field=models.CharField(blank=True, choices=[('권가은', '권가은'), ('김문기', '김문기'), ('김서연', '김서연'), ('노수진', '노수진'), ('배성준', '배성준'), ('신유진', '신유진'), ('오예린', '이예지'), ('장효신', '장효신'), ('최민주', '최민주'), ('김지원', '김지원'), ('김현수', '김현수'), ('김현우', '김현우'), ('서찬혁', '서찬혁'), ('서혜준', '서혜준'), ('이소정', '이소정'), ('임탁균', '임탁균'), ('조예지', '조예지'), ('최유미', '최유미'), ('황재령', '황재령')], max_length=8, null=True),
        ),
    ]
