# Generated by Django 3.0.8 on 2023-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('RePick', 'Repick'), ('바리바리', '바리바리'), ('Hooking', 'Hooking'), ('Dansupport', 'Dansupport'), ('ThearapEase', 'ThearapEase')], default='바리바리', max_length=16),
        ),
    ]
