# Generated by Django 3.0.8 on 2023-05-26 08:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230526_1705'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='part',
            field=models.CharField(choices=[('프론트엔드', '프론트엔드'), ('백엔드', '백엔드')], max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('RePick', 'Repick'), ('바리바리', '바리바리'), ('Hooking', 'Hooking'), ('Dansupport', 'Dansupport'), ('TherapEse', 'TherapEse')], max_length=16),
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
