# Generated by Django 3.0.8 on 2023-05-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230526_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
