# Generated by Django 3.0.8 on 2023-05-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vote_count',
        ),
    ]
