# Generated by Django 3.0.8 on 2023-05-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='part_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='team_vote',
            field=models.BooleanField(default=False),
        ),
    ]
