# Generated by Django 3.0.8 on 2023-05-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230529_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='part',
            field=models.CharField(choices=[('프론트엔드', '프론트엔드'), ('백엔드', '백엔드')], default='백엔드', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('RePick', 'Repick'), ('바리바리', '바리바리'), ('Hooking', 'Hooking'), ('Dansupport', 'Dansupport'), ('TherapEse', 'TherapEse')], default='바리바리', max_length=16),
        ),
    ]
